Implementata la schermata di ricerca
develhope/forecast_app_android3_team1 pull request #3
Opened 2023-01-13 14:02 UTC by laninim

https://trello.com/c/jSWNYaJl  
Implementata la schermata per la ricerca delle città.

2023-01-17 08:51 UTC, vincenzocostagliola requested changes

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/data/DataSet.kt
> +class DataSet {
Cambiaerei il nome in qualcosa di più parlante, altrimenti rischiamo di dover aprire il file ogni volta che cerchiamo un'informazione

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/data/DataSet.kt
> +class DataSet {
Rendilo Object invece di class, così sarà accessibile direttamente, fatto questo il companion object non serve più

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/data/DataSet.kt
> +            RecentSearch("Palermo","12","Soleggiato"),
Avevamo detto che i dettagl isul meteo non erano necessari, visto che è la versione finale, al momento ci interessa solo il nome

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/adapter/RecentSearchAdapter.kt
> +        val nameCity : TextView
si potrebbe aver euna funzione bind con tutta la gestione delle view all'intern osenza dover accedere alle singole view all'esterno del viewholder. Inoltre sarebbe meglio usare il viewbinding (se sappiamo già come usarlo)

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/adapter/RecentSearchAdapter.kt
> +        holder.temperature.text = data[position].temperature + "°"
Le stringhe hardcoded non dovrebbero esistere nel progetto, meglio inserirla nel file delle stringhe

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/java/co/develhope/meteoapp/fragments/SearchFragment.kt
> +    private lateinit var recentSearchList  :  List<RecentSearch>
Non sono necessarie, la lista la puoi recuperare direttamente quando devi inizializzare l'adapter. Idem per la recyclerview, soprattuto se non la riusi in altri punti del fragment

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/res/layout/fragment_search.xml
> +        android:layout_marginTop="16dp"
Spostare tutte le dimensioni hardcoded nel file delle dimensioni

2023-01-17 08:51 UTC, vincenzocostagliola commented on app/src/main/res/layout/recent_search_item.xml
> +        android:textSize="18sp"
Spostare tutte le dimensioni nel file delle dimensioni

2023-01-17 09:31 UTC, laninim commented on app/src/main/java/co/develhope/meteoapp/adapter/RecentSearchAdapter.kt
> +        val nameCity : TextView
Non ho capito bene cosa intendi per una funzione bind, puoi spiegarmelo meglio? devo fare una fun esterna che inizializza le view?

2023-01-26 15:57 UTC, vincenzocostagliola approved these changes

2023-01-26 15:57 UTC, merged